config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  # devise_for :hosts
  devise_for :users, only: [:all],
                     controllers: {
                                  registrations: 'users/registrations',
                                  sessions: 'users/sessions'
                                }
  root 'spaces#index'

  resources :users, only: [:show]
  resources :spaces do
    resources :reservations, only:[:new, :create, :show]
  end
  resources :search do
    get :search, on: :collection
  end
  resources :equipment_infos
  resources :basic_infos
  resources :descriptions
  resources :space_images
  resources :plans
  as :user do
    get 'i/login', to: 'users/sessions#new', as: :new_user_session
    post 'i/login', to: 'users/sessions#create', as: :user_session
    delete 'i/logout', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'i/sign_up', to: 'users/registrations#new', as: :new_user_registration
    post 'i/sign_up', to: 'users/registrations#create', as: :user_registration
  end

  get '*path', controller: 'application', action: 'render_404'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  layout 'search'
  def index
  end

  def search
    @spaces = Space.published.prefecture_key(params[:prefecture_key]).price_min_key(params[:price_min_key]).price_max_key(params[:price_max_key]).capacity_key(params[:capacity_key]).approval_method_key(params[:approval_method_key]).purpose_key(request.url.scan(/purpose_key=([a-z_]+)/).join).page(params[:page]).per(20).order('id DESC')
    parameter_keys = [
        :prefecture_key,
        :price_min_key,
        :price_max_key,
        :capacity_key,
        :approval_method_key,
        :purpose_key,
    ]
    parameter_keys.each do |parameter_key|
      instance_variable_set("@exit_#{ parameter_key.to_s }", params[parameter_key]) if params[parameter_key].present?
    end
    gon.purpose_key = request.url.scan(/purpose_key=([a-z_]+)/).join

    #map.jsに検索結果に表示されているスペースの経度・緯度を渡す
    gon.map_key = ENV['MAP_KEY']
    gon.markerData = []
    @spaces.each do |space|
      gon.markerData << { lat: space.equipment_info.latitude, lng: space.equipment_info.longitude }
    end
  end
end

app/views/search/_condition.html.haml
.search--condition
  = form_tag search_search_index_path, method: :get do
    .search--condition--field
      .search--condition--field--input.search--condition--field--input__prefecture
        = select_tag :prefecture_key, options_for_select(EquipmentInfo.prefectures, selected: "#{@exit_prefecture_key}"), class: 'search--condition--field--input--selector', include_blank: true
        %span.selectbar
        = label_tag 'field-label', '都道府県'
    .search--condition--field
      .search--condition--field--input.search--condition--field--input__prefecture
        = text_field_tag :price_min_key, params[:price_min_key], placeholder: '', class: 'search--condition--field--input--text', value: "#{@exit_price_min_key}"
        %span.selectbar
        = label_tag 'field-label', '最低価格'
    .search--condition--field
      .search--condition--field--input.search--condition--field--input__prefecture
        = text_field_tag :price_max_key, params[:price_max_key], placeholder: '', class: 'search--condition--field--input--text', value: "#{@exit_price_max_key}"
        %span.selectbar
        = label_tag 'field-label', '最高価格'
    .search--condition--field
      .search--condition--field--input.search--condition--field--input__prefecture
        = text_field_tag :capacity_key, params[:capacity_key], placeholder: '', class: 'search--condition--field--input--text', value: "#{@exit_capacity_key}"
        %span.selectbar
        = label_tag 'field-label', '人数'
    .search--condition--field
      .search--condition--field--input.search--condition--field--input__prefecture
        = select_tag :approval_method_key, options_for_select(Plan.reservation_approval_methods, selected: "#{@exit_approval_method_key}"), class: 'search--condition--field--input--selector', include_blank: true
        %span.selectbar
        = label_tag 'field-label', '承認方式'
    .search--condition--hidden-field
      = text_field_tag :purpose_key, params[:purpose_key], placeholder: '', class: 'search--condition--field--input--text', value: "#{@exit_purpose_key}"
    .search--condition--field
      = submit_tag '詳細検索', class: 'btn btn__condition'

app/views/search/_header.html.haml
.search--header
  .header
  .site-header.clearfix.HeaderContainer__SiteHeader-sc-1dznt2s-0.ldcZBj
    %p.fl
      = link_to 'スペースマーケット', root_path, class: 'site-header__logo'
    %div
      %ul.search--header--type
        %li
          = link_to search_search_index_path(params: { purpose_key: 'party' }) do
            .search--header--type__nav.search--header--type__nav__party
              パーティー
        %li
          = link_to search_search_index_path(params: { purpose_key: 'meeting' }) do
            .search--header--type__nav.search--header--type__nav__meeting
              会議
        %li
          = link_to search_search_index_path(params: { purpose_key: 'photo_shoot' }) do
            .search--header--type__nav.search--header--type__nav__photo_shoot
              写真撮影
        %li
          = link_to '' do
            .search--header--type__nav.search--header--type__nav__stay
              民泊
        %li
          .search--header--type__nav.nav-others
            %span.nav-others__title
              その他
            %select.search--header--type__nav--selector{ name: 'others', onChange: 'location.href=value;' }
              %option{ value: 'blank' }
              %option{ value: '/search/search?purpose_key=film_shoot' }
                ロケ撮影
              %option{ value: '/search/search?purpose_key=studio' }
                展示会
              %option{ value: '/search/search?purpose_key=performance' }
                演奏
              %option{ value: '/search/search?purpose_key=sports' }
                スポーツ
              %option{ value: '/search/search?purpose_key=office' }
                オフィス
              %option{ value: '/search/search?purpose_key=wedding' }
                結婚式
              %option{ value: '/search/search?purpose_key=event' }
                イベント
              %option{ value: '/search/search?purpose_key=other' }
                その他
    %div
      %ul.site-header__nav.sm-hide
        %li.site-header__nav-user-name.link-black.link-borderless
          %i.fa.fa-caret-down
        %li
          = link_to '', class: 'site-header__nav-user link-black' do
            - if user_signed_in?
              = image_tag current_user.icon, class: 'site-header__nav-user link-black'
        %li
          = link_to '', class: 'site-header__nav-message link-black' do
            %i.fa.fa-envelope{ style: 'color:lightgray;' }
        %li
          = link_to 'ヘルプ', '', class: 'site-header__nav-help link-black link-borderless help__text'
        - if user_signed_in?
          %li
            = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'site-header__nav-logout link-black'
        - else
          %li
            = link_to 'ログイン', new_user_session_path, method: :get, class: 'site-header__nav-login link-black'
          %li
            = link_to '新規登録', new_user_registration_path, method: :get, class: 'site-header__nav-signup link-black'
        - if user_signed_in?
          %li
            = link_to 'マイページ', user_path(current_user), class: 'site-header__nav-reservation link-black', data: { 'turbolinks' => false }
          %li
            = link_to 'お気に入り', '', class: 'site-header__nav-favorite link-black'
          %li
            = link_to '空きスペースを掲載する', new_equipment_info_path, class: 'site-header__nav-owner link-black', data: { 'turbolinks' => false }

app/views/search/_result.html.haml
.site-main.site-main__result
  .page__stripes.top-page__padding
    .search-list__head-title
      スペース検索結果
      %span
        = "#{ @spaces.length }件"
    .container.top-container
      .top-units__container
        .row
          - @spaces.each.with_index(1) do |space, rank|
            .col-xs-6
              = link_to space_path(id: space.id), { data: { 'turbolinks' => false } }, { class: 'a__top-units' } do
                .md-top-units
                  .md-top-units__image
                    = image_tag(space.space_image.image_files.main.first.file, class: 'md-top-units__image-pict')
                    %p.md-top-units__item-price
                      %span.md-top-units__item-per
                        ¥
                        = number_with_delimiter(space.plan.price_per_day)
                      %span.md-top-units__item-per /日
                      %span.md-top-units__price-icon
                        - if space.plan.reservation_approval_method == '承認なし（今すぐ予約）'
                          = fa_icon 'bolt', class: 'md-top-units__item-instant'
                        = fa_icon 'certificate', class: 'md-top-units__item-top-host'
                        = fa_icon 'arrow-down', class: 'md-top-units__item-icon-discount'
                  .md-top-units__body
                    .md-top-units__body-inner
                      %h3.md-top-units__body-title
                        = space.description.catch_copy.truncate(30)
                      %ul.md-top-units__body-info
                        %li.md-top-units__body-info__capacity
                          = fa_icon 'user', class: 'md-top-units__body-info__icon'
                          = space.basic_info.capacity
                        %li.md-top-units__body-info__prefecture
                          = fa_icon 'map-marker', class: 'md-top-units__body-info__icon'
                          = space.equipment_info.prefecture
                      %p.md-top-units__body-access
                        = space.equipment_info.access.truncate(42)
    = paginate(@spaces)
  .map-content
    #map
    - @spaces.each do |space|
      = link_to space_path(id: space.id), { data: { 'turbolinks' => false } } do
        .select-space.hidden{ class: "select-space#{ @spaces.index(space) }" }
          .select-space--image
            = image_tag(space.space_image.image_files.main.first.file, class: 'select-space--image__pic')
          .select-space--description
            %span.select-space--description--body-title
              = space.description.catch_copy
            %p.select-space--description--price
              %span.select-space--description--price-per
                ¥
                = number_with_delimiter(space.plan.price_per_day)
              %span /日
              %span
                - if space.plan.reservation_approval_method == '承認なし（今すぐ予約）'
                  = fa_icon 'bolt', class: 'select-space--description--price__item-instant'
                = fa_icon 'certificate', class: 'select-space--description--price__item-top-host'
                = fa_icon 'arrow-down', class: 'select-space--description--price__item-icon-discount'

app/views/search/index.html.haml
= render 'search/header'
= render 'search/condition'
= render 'search/result'

app/views/search/search.html.haml
= render 'search/header'
= render 'search/condition'
= render 'search/result'