config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  # devise_for :hosts
  devise_for :users, only: [:all],
                     controllers: {
                                  registrations: 'users/registrations',
                                  sessions: 'users/sessions'
                                }
  root 'spaces#index'

  resources :users, only: [:show]
  resources :spaces do
    resources :reservations, only:[:new, :create, :show]
  end
  resources :search do
    get :search, on: :collection
  end
  resources :equipment_infos
  resources :basic_infos
  resources :descriptions
  resources :space_images
  resources :plans
  as :user do
    get 'i/login', to: 'users/sessions#new', as: :new_user_session
    post 'i/login', to: 'users/sessions#create', as: :user_session
    delete 'i/logout', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'i/sign_up', to: 'users/registrations#new', as: :new_user_registration
    post 'i/sign_up', to: 'users/registrations#create', as: :user_registration
  end

  get '*path', controller: 'application', action: 'render_404'

end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_one  :equipment_info, dependent: :destroy
  has_one  :basic_info, dependent: :destroy
  has_one  :description, dependent: :destroy
  has_one  :plan, dependent: :destroy
  has_one  :space_image, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :reservations, dependent: :destroy

  validates :status, space_status_validation: true, on: :update

  scope :published, -> { where(published: true) }
  scope :party,  -> { joins(basic_info: [:purpose]).where('party = ?', 1) }
  scope :meeting, -> { joins(basic_info: [:purpose]).where('meeting = ?', 1) }
  scope :photo_shoot, -> { joins(basic_info: [:purpose]).where('photo_shoot = ?', 1) }
  scope :film_shoot, -> { joins(basic_info: [:purpose]).where('film_shoot = ?', 1) }
  scope :sports, -> { joins(basic_info: [:purpose]).where('sports = ?', 1) }
  scope :by_likes_count, -> { order('likes_count DESC') }
  enum status: %i(draft published)

  scope :prefecture_key, -> (params) { joins(:equipment_info).where('prefecture LIKE(?)', params) if params.present? }
  scope :price_min_key, -> (params) { joins(:plan).where('price_per_day >= ?', params) if params.present? }
  scope :price_max_key, -> (params) { joins(:plan).where('price_per_day <= ?', params) if params.present? }
  scope :capacity_key, -> (params) { joins(:basic_info).where('capacity >= ?', params) if params.present? }
  scope :approval_method_key, -> (params) { joins(:plan).where('reservation_approval_method = ?', params) if params.present? }
  scope :purpose_key, -> (params) { joins(basic_info: [:purpose]).where("#{params} = ?", 1) if params.present? }
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController

  before_action :set_space, except: [:index, :show]
  before_action :check_current_user, except: [:index, :show]

  def index
    @party_spaces = Space.published.party.by_likes_count.limit(3).order('id DESC')
    @meeting_spaces = Space.published.meeting.by_likes_count.limit(3).order('id DESC')
    @photo_shoot_spaces = Space.published.photo_shoot.by_likes_count.limit(3).order('id DESC')
    @film_shoot_spaces = Space.published.film_shoot.by_likes_count.limit(3).order('id DESC')
    @sports_spaces = Space.published.sports.by_likes_count.limit(3).order('id DESC')
    #いいね機能を実装後に修正する
    @favorite_spaces = Space.published.all.limit(3).order('id DESC')
    #各目的別スペース登録数
    @spaces_count = Space.published.length
    @party_spaces_count = Space.published.party.length
    @meeting_spaces_count = Space.published.meeting.length
    @photo_shoot_spaces_count = Space.published.photo_shoot.length
    @film_shoot_spaces_count = Space.published.film_shoot.length
    @sports_spaces_count = Space.published.sports.length
  end

  def edit
    render layout: 'new_space'
  end

  def update
    begin
      @space.update!(status: 1)
      redirect_to edit_space_path(@space)
    rescue ActiveRecord::RecordInvalid => e
      logger.error e
      redirect_to edit_space_path(@space), alert: '未入力の情報があります'
    end
  end

  def show
    clear_notice
    if Space.find(params[:id]).published?
      @space = Space.published.find(params[:id])
      if @space.space_image.image_files.sub.present?
        @sub_images = @space.space_image.image_files.sub
      else
        @sub_images = []
      end
      gon.map_key = ENV["MAP_KEY"]
      gon.markerData = []
      gon.markerData << { lat: @space.equipment_info.latitude, lng: @space.equipment_info.longitude }
      render :layout => 'space_show'
    else
      render_404
    end
  end


  def destroy
    @space.destroy
    redirect_to user_path(current_user)
  end

  private

  def check_current_user
    space = Space.find(params[:id])
    render_404 unless space.user_id == current_user.id
  end

  def set_space
    @space = Space.find(params[:id])
  end

  def clear_notice
    flash.discard(:notice)
  end
end

app/views/spaces/_banner.html.haml
.top-static__banner
  .top-static__banner__container
    %h3.top-static__banner-title あなたもホストになってみませんか
    %p.top-static__banner-text お持ちのスペースを今すぐ有効活用。あらゆるスペースが登録可能です。
    %a.btn.btn-default.top-static__banner-button もっと詳しく

app/views/spaces/_favorite_ranking.html.haml
.site-main
  .page__stripes.top-page__padding
    .container.top-container
      .top-title__container.clearfix
        %h2.top-title
          お気に入り
      .top-units__container
        .row
          - @favorite_spaces.each.with_index(1) do |space, rank|
            //カードここから//
            .col-xs-4
              = link_to space_path(id: space.id), class: "a__top-units", data: { "turbolinks" => false } do
                .md-top-units
                  .md-top-units__image
                    .top-units-ranking.units-ranking.units-ranking__icon{class: "units-ranking__no#{rank}"}
                      .units-ranking__icon-body
                        %span.units-ranking__icon-number #{rank}
                    = image_tag(space.space_image.image_files.main.first.file, class: "md-top-units__image-pict")
                    %p.md-top-units__item-price
                      %span.md-top-units__item-per
                        ¥
                        = number_with_delimiter(space.plan.price_per_day)
                      %span.md-top-units__item-per /日
                      %span.md-top-units__price-icon
                        - if space.plan.reservation_approval_method == "承認なし（今すぐ予約）"
                          = fa_icon "bolt", class: "md-top-units__item-instant"
                        = fa_icon "certificate", class: "md-top-units__item-top-host"
                        = fa_icon "arrow-down", class: "md-top-units__item-icon-discount"
                  .md-top-units__body
                    .md-top-units__body-inner
                      %h3.md-top-units__body-title
                        = space.description.catch_copy.truncate(26)
                      %ul.md-top-units__body-info
                        %li
                          = fa_icon "user", class: "md-top-units__body-info__icon"
                          = space.basic_info.capacity
                        %li
                          = fa_icon "map-marker", class: "md-top-units__body-info__icon"
                          = space.equipment_info.prefecture
      .sm-hide.top-more__area
        %a.top-more__area-link お気に入りスペースをすべて見る >

app/views/spaces/_header.html.haml
.site-header__sponsoredmatch.site-header__sponsoredmatch_type1
  .site-header__sponsoredmatch.site-
    .site-header__sponsoredmatch.site-header__sponsoredmatch_type1
.header
  .site-header.clearfix.HeaderContainer__SiteHeader-sc-1dznt2s-0.ldcZBj
    %p.fl
      = link_to "スペースマーケット", root_path, class: "site-header__logo"
    %div
      %ul.site-header__nav.sm-hide
        %li.site-header__nav-user-name.link-black.link-borderless
          %i.fa.fa-caret-down
        %li
          = link_to "", class: "site-header__nav-user" do
            - if user_signed_in?
              = image_tag current_user.icon, class: "site-header__nav-user"
        %li
          = link_to "", class: "site-header__nav-message" do
            %i.fa.fa-envelope{style: "color:lightgray;"}
        %li
          = link_to "ヘルプ", "", class: "site-header__nav-help link-black link-borderless help__text"
        - if user_signed_in?
          %li
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "site-header__nav-help link-black"
        - else
          %li
            = link_to "ログイン", new_user_session_path, method: :get, class: "site-header__nav-help link-black"
          %li
            = link_to "新規登録", new_user_registration_path, method: :get, class: "site-header__nav-help link-black", data: { "turbolinks" => false }
        - if user_signed_in?
          %li
            = link_to "マイページ", user_path(current_user), class: "site-header__nav-reservation link-black"
          %li
            = link_to "お気に入り", "", class: "site-header__nav-favorite link-black"
          %li
            = link_to "空きスペースを掲載する", new_equipment_info_path, class: "site-header__nav-owner link-black", data: { "turbolinks" => false }
.site-main
  .top-mv
    %p.service-logo
    %h1.top-information__sub
      = "#{@spaces_count}件のレンタルスペースから目的に合ったスペースをかんたん予約"
    .page__information
      .top-menu__container
        .container
          %ul.row
            %li.top-menu__list.col-xs-4
              = link_to search_search_index_path(params: { purpose_key: 'party' }), class: "top-menu__list-button mdc-elevation--z2" do
                %img.top-menu__list-button-img{:alt => "パーティー", :src => "//cdnspacemarket.com/packs-production/images/www/icon/party_blue-284ad75134.svg"}/
                %span.top-menu__list-button-text
                  パーティー
                  %span.top-menu__list-button-num
                    = "#{@party_spaces_count}件"
                %i.fa.fa-angle-right.yajirusi

            %li.top-menu__list.col-xs-4
              = link_to search_search_index_path(params: { purpose_key: 'meeting' }), class: "top-menu__list-button mdc-elevation--z2" do
                %img.top-menu__list-button-img{:alt => "会議", :src => "//cdnspacemarket.com/packs-production/images/www/icon/class_blue-e05f553eaf.svg"}/
                %span.top-menu__list-button-text
                  会議
                  %span.top-menu__list-button-num
                    = "#{@meeting_spaces_count}件"
                %i.fa.fa-angle-right.yajirusi
            %li.top-menu__list.col-xs-4
              = link_to "", class: "top-menu__list-button mdc-elevation--z2" do
                %img.top-menu__list-button-img{:alt => "民泊", :src => "//cdnspacemarket.com/packs-production/images/www/icon/stay_blue-e36c43aef6.svg"}/
                %span.top-menu__list-button-text
                  民泊
                  %span.top-menu__list-button-num 0件
                %i.fa.fa-angle-right.yajirusi
        .container
          %ul.row
            %li.top-menu__list.top-menu__list-second.col-xs-3
              = link_to search_search_index_path(params: { purpose_key: 'photo_shoot' }), class: "top-menu__list-button mdc-elevation--z2" do
                %img.top-menu__list-button-img{:alt => "", :src => "//cdnspacemarket.com/packs-production/images/www/icon/photo_shoot_blue-9d526ca0c6.svg"}/
                %span.top-menu__list-button-text
                  写真撮影
                  %span.top-menu__list-button-num
                    = "#{@photo_shoot_spaces_count}件"
                %i.fa.fa-angle-right.yajirusi
            %li.top-menu__list.top-menu__list-second.col-xs-3
              = link_to search_search_index_path(params: { purpose_key: 'film_shoot' }), class: "top-menu__list-button mdc-elevation--z2" do
                %img.top-menu__list-button-img{:alt => "", :src => "//cdnspacemarket.com/packs-production/images/www/icon/film_shoot_blue-b0d90574c8.svg"}/
                %span.top-menu__list-button-text
                  ロケ撮影
                  %span.top-menu__list-button-num
                    = "#{@film_shoot_spaces_count}件"
                %i.fa.fa-angle-right.yajirusi
            %li.top-menu__list.top-menu__list-second.col-xs-3
              = link_to search_search_index_path(params: { purpose_key: 'sports' }), class: "top-menu__list-button mdc-elevation--z2" do
                %img.top-menu__list-button-img{:alt => "", :src => "//cdnspacemarket.com/packs-production/images/www/icon/sports_blue-d0e5f50187.svg"}/
                %span.top-menu__list-button-text
                  スポーツ
                  %span.top-menu__list-button-num
                    = "#{@sports_spaces_count}件"
                %i.fa.fa-angle-right.yajirusi
            %li.top-menu__list.top-menu__list-second.col-xs-3
              .top-menu__list-button.mdc-elevation--z2{:href => "/search?event_type=other"}
                %img.top-menu__list-button-img{:alt => "", :src => "//cdnspacemarket.com/packs-production/images/www/icon/other_blue-dbd2f4ef89.svg"}/
                %span.top-menu__list-button-text その他
                %select.search--header--type__nav--selector__main{ name: "others", onChange: "location.href=value;" }
                  %option{ value: "blank" }
                  %option{ value: "/search/search?purpose_key=event" }
                    イベント
                  %option{ value: "/search/search?purpose_key=performance" }
                    演奏
                  %option{ value: "/search/search?purpose_key=studio" }
                    展示会
                  %option{ value: "/search/search?purpose_key=office" }
                    オフィス
                  %option{ value: "/search/search?purpose_key=wedding" }
                    結婚式
      .top-menu__other-search
        .top-menu__icon
          %i.fa.fa-search
          %h3.top-menu__other-ttl カテゴリーから探す
          %ul.top-flow__list
            %li
              %a エリア
            %li.left-border
              %a 人数
            %li.left-border
              %a 会場タイプ
            %li.left-border
              %a アメニティ

app/views/spaces/_other_header.html.haml
.site-other-header
  .site-header__sponsoredmatch.site-header__sponsoredmatch_type1
    .site-header__sponsoredmatch.site-
      .site-header__sponsoredmatch.site-header__sponsoredmatch_type1
  .other-header
    .site-header.clearfix.HeaderContainer__SiteHeader-sc-1dznt2s-0.ldcZBj
      %div
        %p.fl
          = link_to "スペースマーケット", root_path, class: "site-header__logo"
      %div
        %ul.site-header__category
          %li.site-header__search-menu-item
            %a.site-header__search-menu-button{:href => "#"} パーティー
          %li.site-header__search-menu-item
            %a.site-header__search-menu-button{:href => "#"} 会議
          %li.site-header__search-menu-item
            %a.site-header__search-menu-button{:href => "#"} 写真撮影
          %li.site-header__search-menu-item
            %a.site-header__search-menu-button{:href => "#"} 民泊
          %li.site-header__search-menu-item.site-header__search-menu-item-others
            %a.site-header__search-menu-button{:href => "#"} その他
            %i.fa.fa-caret-down
            %select.CategorySearchHeader__SelectBox-mctj7e-0.jkvhPY{:name => "others"}
              %option{:value => ""}
              %option{:value => "film_shoot"} ロケ撮影
              %option{:value => "studio"} 展示会
              %option{:value => "performance"} 演奏
              %option{:value => "sports"} スポーツ
              %option{:value => "office"} オフィス
              %option{:value => "wedding"} 結婚式
              %option{:value => "event"} イベント
              %option{:value => "other"} その他
      .site-header--float
        %ul.site-header__nav.sm-hide
          - if user_signed_in?
            %li.site-header__nav-user-name.link-black.link-borderless
              %i.fa.fa-caret-down
            %li
              = link_to root_path, class: "site-header__nav-user" do
                = image_tag current_user.icon, class: "site-header__nav-user"
            %li
              = link_to root_path, class: "site-header__nav-message" do
                %i.fa.fa-envelope
            %li
              = link_to "ヘルプ", user_path(current_user), class: "site-header__nav-help link-black link-borderless help__text"
            %li
              = link_to "お気に入り", root_path, class: "site-header__nav-favorite link-black"
            %li
              = link_to "マイページ", user_path(current_user), class: "site-header__nav-owner link-black"

  .site-main
    .Breadcrumbs-sc-1qbqhcr-0.dsvKPy
      %ol{:itemscope => "", :itemtype => "http://data-vocabulary.org/Breadcrumb"}
        %li.Breadcrumbs__BreadcrumbsItem-sc-1qbqhcr-1.bTNhRS
          %a.Breadcrumbs__BreadcrumbsItemLink-sc-1qbqhcr-2.gDRZcs{:href => "/"}
            %span トップ &nbsp; > &nbsp;
        %li.Breadcrumbs__BreadcrumbsItem-sc-1qbqhcr-1.bTNhRS
          %a.Breadcrumbs__BreadcrumbsItemLink-sc-1qbqhcr-2.gDRZcs{:href => "#"}
            %span #{@space.equipment_info.prefecture} &nbsp; > &nbsp;
        %li.Breadcrumbs__BreadcrumbsItem-sc-1qbqhcr-1.bTNhRS
          %a.Breadcrumbs__BreadcrumbsItemLink-sc-1qbqhcr-2.gDRZcs{:href => "#"}
            %span #{@space.description.catch_copy} &nbsp; > &nbsp;
        %li.Breadcrumbs__BreadcrumbsItem-sc-1qbqhcr-1.bTNhRS
          %span #{@space.description.catch_copy}

app/views/spaces/_ranking.html.haml
.site-main
  .page__stripes.top-page__padding{class: "#{back}"}
    .container.top-container
      .top-title__container.clearfix
        %h2.top-title
          = title
      .top-units__container
        .row
          - spaces.each.with_index(1) do |space, rank|
            .col-xs-4
              = link_to space_path(id: space.id), class: "a__top-units", data: { "turbolinks" => false } do
                .md-top-units
                  .md-top-units__image
                    .top-units-ranking.units-ranking.units-ranking__icon{class: "units-ranking__no#{rank}"}
                      .units-ranking__icon-body
                        %span.units-ranking__icon-number #{rank}
                    = image_tag(space.space_image.image_files.main.first.file, class: "md-top-units__image-pict")
                    %p.md-top-units__item-price
                      %span.md-top-units__item-per
                        ¥
                        = number_with_delimiter(space.plan.price_per_day)
                      %span.md-top-units__item-per /日
                      %span.md-top-units__price-icon
                        - if space.plan.reservation_approval_method == "承認なし（今すぐ予約）"
                          = fa_icon "bolt", class: "md-top-units__item-instant"
                        = fa_icon "certificate", class: "md-top-units__item-top-host"
                        = fa_icon "arrow-down", class: "md-top-units__item-icon-discount"
                  .md-top-units__body
                    .md-top-units__body-inner
                      %h3.md-top-units__body-title
                        = space.description.catch_copy.truncate(26)
                      %ul.md-top-units__body-info
                        %li
                          = fa_icon "user", class: "md-top-units__body-info__icon"
                          = space.basic_info.capacity
                        %li
                          = fa_icon "map-marker", class: "md-top-units__body-info__icon"
                          = space.equipment_info.prefecture
      .sm-hide.top-more__area
        = link_to "#{title}で利用できるスペースをすべて見る >", search_search_index_path(params: { purpose_key: "#{purpose_key}" }), class: "top-more__area-link"

app/views/spaces/_recommend_ranking.html.haml
.site-main
  .page__stripes.top-page__padding.graybackground
    .container.top-container
      .top-title__container.clearfix
        %h2.top-title おすすめスペースまとめ
      .top-units__container
        .row
          .col-xs-3.md-matome-list
            %a.a__top-units
              .md-top-units
                .md-matome-image
                  %img.md-matome-image__pict{:alt => "キッチンが使えるレンタルスペース・スタジオまとめ", :src => "https://cdnspacemarket.com/uploads/features/31/72590ea9d87dbe358f1ac159efb8699b.jpg"}/
                .md-matome-subtitle キッチンが使えるレンタルスペース・スタジオまとめ
          .col-xs-3.md-matome-list
            %a.a__top-units
              .md-top-units
                .md-matome-image
                  %img.md-matome-image__pict{:alt => "手ぶらで貸切バーベキューのできるレンタルスペースまとめ", :src => "https://cdnspacemarket.com/uploads/features/66/b71a1d9a7a6c259ba2d5f871c7f21945.jpg"}/
                .md-matome-subtitle 手ぶらで貸切バーベキューのできるレンタルスペースまとめ
          .col-xs-3.md-matome-list
            %a.a__top-units
              .md-top-units
                .md-matome-image
                  %img.md-matome-image__pict{:alt => "室内キャンプ・おうちキャンプができるスペースまとめ", :src => "https://cdnspacemarket.com/uploads/features/273/7c39fa5cfa48487386de29ffbfc7b158.jpg"}/
                .md-matome-subtitle 室内キャンプ・おうちキャンプができるスペースまとめ
          .col-xs-3.md-matome-list
            %a.a__top-units
              .md-top-units
                .md-matome-image
                  %img.md-matome-image__pict{:alt => "パジャマパーティー #パジャパ におすすめの女子会部屋まとめ", :src => "https://cdnspacemarket.com/uploads/features/299/7638d3dca2aa1be2e1609177555865b4.png"}/
                .md-matome-subtitle パジャマパーティー #パジャパ におすすめの女子会部屋まとめ

      .sm-hide.top-more__area
        %a.top-more__area-link おすすめスペースまとめをもっと見る >

app/views/spaces/_regist_banner_blue.html.haml
.mod-banner.mod-banner__guest
  .container
    %h3 今すぐ会員登録して、スペースを貸し借りしてみよう
    %p たったの1分でかんたん登録。もちろん無料です。
    = link_to "新規登録（無料）", new_user_registration_path, class: "mod-banner"

app/views/spaces/_regist_yellow.html.haml
.page__stripes.graybackground
  .top-regist
    .top-regist__inner
      .top-regist__unit
        %p.top-regist__title-guide 新規アカウント登録して頂いた方全員に
        %p.top-regist__everyone もれなく
        %span.top-regist__title ¥
        %span.top-regist__title-large 1,000
        %span.top-regist__title-small 相当のポイントをプレゼント！
      .top-regist__all-space 全てのスペースにご利用可能です
      .top-regist__text
        %span.top-regist__slash-white ＼
        %span.top-regist__slash おトクにスペースを借りてみよう！
        %span.top-regist__slash-white ／
    .top-regist__button_wrap
      = link_to "新規アカウント登録はこちら", new_user_registration_path, class: "top-regist__button"

app/views/spaces/edit.html.haml
.main-contents
  .main-contents__contents
    .flow-header__container
      %h2.flow-header__title スペース掲載
      .flow-header__description スペースの情報を登録して、スペースを掲載することができます。スペースの編集はいつでも可能です。
    .status-page__container
      .status-page__message-wrapper
        - if flash.any?
          .message__container.message-alert
            %span.message__text
              = flash[:alert]
        - else
          .message__container
            %span.message__text
              スペースの作成が完了しました！
      .status-page__card
        .edit-publish-feature__container
          .publish-feature-card__container
            .publish-feature-card__icon-wrapper
              %i.fa.fa-home.icon
            .publish-feature-card__label-container
              .publish-feature-card__title スペースの作成
              %p.publish-feature-card__caption 貸し出すスペースの紹介や注意事項、価格、写真などを登録してスペースを作成しましょう。
          %hr.publish-feature-card__border
          .publish-feature-card__container
            %ul.edit-publish-feature__row-list
              -# 1施設情報
              %li.edit-publish-feature__row-list-item
                .setting-row__container
                  .setting-row__head
                    - if @space.equipment_info.present?
                      .setting-row__status.status-ok
                        %span.status 完了
                    - else 
                      .setting-row__status.status-ng
                        %span.status 未完
                  .setting-row__item-name 1 施設情報
                  .setting-row__link-text-wrapper
                    - if @space.equipment_info.present?
                      = link_to "編集", edit_equipment_info_path(@space.equipment_info)
              -# 2基本情報
              %li.edit-publish-feature__row-list-item
                .setting-row__container
                  .setting-row__head
                    - if @space.basic_info.present?
                      .setting-row__status.status-ok
                        %span.status 完了
                    - else 
                      .setting-row__status.status-ng
                        %span.status 未完
                  .setting-row__item-name 2 基本情報
                  .setting-row__link-text-wrapper
                    - if @space.basic_info.present?
                      = link_to "編集", edit_basic_info_path(@space.basic_info)
                    - elsif @space.equipment_info.present?
                      = link_to "追加", new_basic_info_path(space_id: @space)
              -# 3説明文
              %li.edit-publish-feature__row-list-item
                .setting-row__container
                  .setting-row__head
                    - if @space.description.present?
                      .setting-row__status.status-ok
                        %span.status 完了
                    - else 
                      .setting-row__status.status-ng
                        %span.status 未完
                  .setting-row__item-name 3 説明文
                  .setting-row__link-text-wrapper
                    - if @space.description.present?
                      = link_to "編集", edit_description_path(@space.description)
                    - elsif @space.basic_info.present?
                      = link_to "追加", new_description_path(space_id: @space)
              -# 4写真
              %li.edit-publish-feature__row-list-item
                .setting-row__container
                  .setting-row__head
                    - if @space.space_image.present?
                      .setting-row__status.status-ok
                        %span.status 完了
                    - else 
                      .setting-row__status.status-ng
                        %span.status 未完
                  .setting-row__item-name 4 写真
                  .setting-row__link-text-wrapper
                    - if @space.space_image.present?
                      = link_to "編集", edit_space_image_path(@space.space_image)
                    - elsif @space.description.present?
                      = link_to "追加", new_space_image_path(space_id: @space)
              -# 5プラン
              %li.edit-publish-feature__row-list-item
                .setting-row__container
                  .setting-row__head
                    - if @space.plan.present?
                      .setting-row__status.status-ok
                        %span.status 完了
                    - else 
                      .setting-row__status.status-ng
                        %span.status 未完
                  .setting-row__item-name 5 プラン
                  .setting-row__link-text-wrapper
                    - if @space.plan.present?
                      = link_to "編集", edit_plan_path(@space.plan)
                    - elsif @space.space_image.present?
                      = link_to "追加", new_plan_path(space_id: @space)
    .status-page__bottom
      .status-page__bottom__text__container
        - if @space.status == "draft"
          .status-page__bottom__text__inner 必要な情報をすべて入力すると審査に申請することができます。
      .status-page__bottom__button__container
        - if @space.status == "draft"
          = button_to "掲載審査", space_path(@space), method: :patch, class: "status-page__bottom__button__inner btn", id: "publish-btn", disabled: true
        - if @space.status == "published"
          .status-page__bottom__button__inner.published 掲載中です
    .status-page__to-mypage
      = link_to user_path(current_user) do
        %i.fas.fa-reply
        マイページへ戻る

app/views/spaces/index.html.haml
= render 'header'
= render 'favorite_ranking'
= render 'recommend_ranking'
= render 'regist_yellow'
= render partial: 'ranking', locals: { spaces: @party_spaces, title: "パーティー", purpose_key: "party", back: "" }
= render partial: 'ranking', locals: { spaces: @meeting_spaces, title: "会議・研修", purpose_key: "meeting", back: "graybackground" }
= render 'banner'
= render partial: 'ranking', locals: { spaces: @photo_shoot_spaces, title: "写真撮影", purpose_key: "photo_shoot", back: "" }
= render partial: 'ranking', locals: { spaces: @film_shoot_spaces, title: "ロケ撮影", purpose_key: "film_shoot", back: "graybackground" }
= render partial: 'ranking', locals: { spaces: @sports_spaces, title: "スポーツ・フィットネス", purpose_key: "sports", back: "" }
= render 'regist_banner_blue'