config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  # devise_for :hosts
  devise_for :users, only: [:all],
                     controllers: {
                                  registrations: 'users/registrations',
                                  sessions: 'users/sessions'
                                }
  root 'spaces#index'

  resources :users, only: [:show]
  resources :spaces do
    resources :reservations, only:[:new, :create, :show]
  end
  resources :search do
    get :search, on: :collection
  end
  resources :equipment_infos
  resources :basic_infos
  resources :descriptions
  resources :space_images
  resources :plans
  as :user do
    get 'i/login', to: 'users/sessions#new', as: :new_user_session
    post 'i/login', to: 'users/sessions#create', as: :user_session
    delete 'i/logout', to: 'users/sessions#destroy', as: :destroy_user_session
    get 'i/sign_up', to: 'users/registrations#new', as: :new_user_registration
    post 'i/sign_up', to: 'users/registrations#create', as: :user_registration
  end

  get '*path', controller: 'application', action: 'render_404'

end

app/models/user.rb
class User < ApplicationRecord
  devise   :database_authenticatable, :registerable, :recoverable, :rememberable

  has_many :reservations, dependent: :destroy
  has_many :likes,        dependent: :destroy
  has_many :spaces,       dependent: :destroy

  mount_uploader :icon, IconUploader

  validates :first_name,                      first_name_validation: true
  validates :last_name,                       last_name_validation: true
  validates :email,                           email_validation: true
  validates :password,                        password_validation: true
  validates :accepted,                        accepted_validation: true
  validate  :password_confirmation_validates
end

def password_confirmation_validates
  if password_confirmation != password
    errors.add(:password_confirmation, 'パスワード（確認）とパスワードの入力が一致しません。')
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout 'registrations'

  def new
    @user = User.new
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'registrations'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_current_user, only: [:show]
  def show
    @reservations = Reservation.where(user_id: params[:id]).order('day ASC')
    @spaces = Space.where(user_id: params[:id])
  end

  private
  def check_current_user
    render_404 unless user_signed_in? && (current_user.id == params[:id].to_i)
  end
end

app/views/users/show.html.haml
= render 'search/header'

.site-main
  .page__even
    .container
      .row
        .toggle
          %a.toggle-button
            %p.userSpace.check  あなたのスペース一覧
            %p.reserve 予約一覧

        .reservation-list.none
          .reservation-list__head-container
            .reservation-list__title
              %p 予約一覧
          - @reservations.each do |reservation|
            .user-space__contents
              .user-space__content
                .user-space__content__image
                  - if reservation.space.space_image
                    = image_tag(reservation.space.space_image.image_files.main.first.file, class: 'preview')
                  - else
                    = image_tag('spesma3.png', class: 'preview')
                .user-space__content__info
                  .user-space__content__info__space-info
                    .user-space__content__info__space-copy
                    - if reservation.space.description
                      %p #{ reservation.space.description.catch_copy }
                  .user-space__content__info__space-address
                    .space-address__left
                      %i.far.fa-calendar-alt
                    .space-address__right
                      %p #{ reservation.day }
        .user-space
          .user-space__head
            .user-space__title
              %p あなたのスペース一覧
          - @spaces.each do |space|
            .user-space__contents
              .user-space__content
                .user-space__content__image
                  - if space.space_image
                    = image_tag(space.space_image.image_files.main.first.file, class: 'preview')
                  - else
                    = image_tag('spesma3.png', class: 'preview')
                .user-space__content__info
                  .user-space__content__info__space-info
                    .user-space__content__info__space-copy
                    - if space.description
                      %p #{ space.description.catch_copy }
                  .user-space__content__info__space-address
                    .space-address__left
                      %i.fas.fa-map-marker-alt
                    .space-address__right
                      %p #{ space.equipment_info.prefecture }#{ space.equipment_info.city_name }#{ space.equipment_info.street_name }
                      - if space.equipment_info.building_name
                        #{ space.equipment_info.building_name }
                  .user-space__content__info__buttons
                    .space-edit
                      = link_to 'スペース情報の編集', edit_space_path(space), class: 'space-edit__button'
                    .space-destroy
                      = link_to 'スペース情報の削除', space_path(space), method: :delete, class: 'space-destroy__button', data: { confirm: '本当に削除しますか？' }